// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
// Generated by scripts/schema-to-markdown.py from public/schemas/*.x-group.
import schemaReference from './src/schema-sidebar.json' with { type: 'json' };

// https://astro.build/config
export default defineConfig({
	// Retired pages, plus the flat v4 paths that shipped app builds still open. Those arrive here
	// through the host-level help.encounter.plus/* → docs.encounter.plus/* redirect.
	redirects: {
		'/guides/web-client-faq': '/guides/remote-play/',
		'/remote-play': '/guides/remote-play/',
		'/special-thanks': '/guides/special-thanks/',
		// Retired in the v5 guides restructure.
		'/guides/encounter-management': '/guides/encounters/',
		'/guides/tips-and-tricks': '/guides/how-it-works/',
		'/guides/battle-map': '/guides/battle-maps/',
	},
	integrations: [
		starlight({
			title: 'Encounter+ Docs',
			logo: {
       	light: './src/assets/logo-light.webp',
    		dark: './src/assets/logo-dark.webp',
				replacesTitle: true,
      },
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/encounterplus/docs' }],
			customCss: [
        // Relative path to your custom CSS file
        './src/styles/custom.css',
      ],
			sidebar: [
				{
          label: "About",
          items: [
            { label: "Introduction", link: "/about/intro" },
            { label: "Upgrading from v4", link: "/about/upgrading/" },
            { label: "FAQ", link: "/about/faq/" },
          ],
        },
				{
          label: "Guides",
          items: [
            { label: "Quick Start", link: "/guides/quick-start/" },
            { label: "How it works", link: "/guides/how-it-works/" },
            { label: "The Library", link: "/guides/library/" },
            { label: "Campaigns & Modules", link: "/guides/campaigns-and-modules/" },
            { label: "Encounters & Combat", link: "/guides/encounters/" },
						{
              label: "Battle Maps",
              items: [
                { label: "Overview", link: "/guides/battle-maps/" },
                { label: "Tokens", link: "/guides/battle-maps/tokens/" },
                { label: "Line of Sight & Fog", link: "/guides/battle-maps/line-of-sight/" },
                { label: "Drawing, Markers & Effects", link: "/guides/battle-maps/drawing-and-effects/" },
              ],
            },
            { label: "The Player Screen", link: "/guides/player-screen/" },
            { label: "Remote Play", link: "/guides/remote-play/" },
            { label: "Dice & Roll Tables", link: "/guides/dice/" },
            { label: "Import and Export", link: "/guides/import-and-export/" },
            { label: "Game Systems", link: "/guides/game-systems/" },
            { label: "Video Tutorials", link: "/guides/tutorials/" },
            { label: "Special Thanks", link: "/guides/special-thanks/" },
          ],
        },
				{
					label: 'Settings',
					items: [
						{ label: 'Overview', link: '/settings/overview/' },
						{ label: 'Content', link: '/settings/content/' },
						{ label: 'Combat', link: '/settings/combat/' },
						{ label: 'Dice Roller', link: '/settings/dice-roller/' },
						{ label: 'Battle Map', link: '/settings/battle-map/' },
						{ label: 'External Screen', link: '/settings/external-screen/' },
						{ label: 'Remote Play', link: '/settings/remote-play/' },
						{ label: 'Advanced', link: '/settings/advanced/' },
						{ label: 'Purchases', link: '/settings/purchases/' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'URL Scheme', link: '/reference/url-scheme/' },
						{ label: 'Legacy XML', link: '/reference/legacy-xml/overview/' },
						...schemaReference,
					],
				},
			],
		}),
	],
});
