// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
// Generated by scripts/schema-to-markdown.py from public/schemas/*.x-group.
import schemaReference from './src/schema-sidebar.json' with { type: 'json' };

// https://astro.build/config
export default defineConfig({
	// Retired pages and the address the app's in-app Help button still uses.
	redirects: {
		'/guides/web-client-faq': '/guides/remote-play/',
		'/remote-play': '/guides/remote-play/',
	},
	integrations: [
		starlight({
			title: 'Encounter+ Docs',
			logo: {
       	light: './src/assets/logo-light.webp',
    		dark: './src/assets/logo-dark.webp',
				replacesTitle: true,
      },
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/encounterplus/docs' }],
			customCss: [
        // Relative path to your custom CSS file
        './src/styles/custom.css',
      ],
			sidebar: [
				{
          label: "About",
          items: [
            { label: "Introduction", link: "/about/intro" },
            { label: "Upgrading from v4", link: "/about/upgrading/" },
            { label: "FAQ", link: "/about/faq/" },
          ],
        },
				{
          label: "Guides",
          items: [
            { label: "Quick start", link: "/guides/quick-start/" },
            { label: "Campaigns & Modules", link: "/guides/campaigns-and-modules/" },
            { label: "Encounter Management", link: "/guides/encounter-management/" },
            { label: "Library", link: "/guides/library/" },
            { label: "Battle maps", link: "/guides/battle-map/" },
						{
              label: "Battle Maps",
              items: [
                { label: "Line of Sight", link: "/guides/battle-maps/line-of-sight/" },
              ],
            },
            { label: "Import and Export", link: "/guides/import-and-export/" },
            { label: "Remote Play", link: "/guides/remote-play/" },
            { label: "Tips and Tricks", link: "/guides/tips-and-tricks/" },
            { label: "Tutorials", link: "/guides/tutorials/" },
            { label: "Special Thanks", link: "/guides/special-thanks/" },
          ],
        },
				{
					label: 'Settings',
					items: [
						{ label: 'Overview', link: '/settings/overview/' },
						{ label: 'Content', link: '/settings/content/' },
						{ label: 'Combat', link: '/settings/combat/' },
						{ label: 'Dice Roller', link: '/settings/dice-roller/' },
						{ label: 'Battle Map', link: '/settings/battle-map/' },
						{ label: 'External Screen', link: '/settings/external-screen/' },
						{ label: 'Remote Play', link: '/settings/remote-play/' },
						{ label: 'Advanced', link: '/settings/advanced/' },
						{ label: 'Purchases', link: '/settings/purchases/' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'URL Scheme', link: '/reference/url-scheme/' },
						{ label: 'Legacy XML', link: '/reference/legacy-xml/overview/' },
						...schemaReference,
					],
				},
			],
		}),
	],
});
